# Generated by Django 3.2.7 on 2021-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True)),
                ('author_name', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
